spring.application.name=springJavaFX
spring.main.web-application-type=none
application.title=Spring Boot and Java FX

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
driverClassName=org.sqlite.JDBC
url=jdbc:sqlite:data/solfeggio.db
username=sa
password=sa

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false